### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by konkyri** [miguelantonio/storm-esper-bolt#7]
Can you please tell me how to run the examples,such as the soda test?
It seems there is no main class.I have tried making a new project,using the classes and building a main class but there seems to be a problem with the storm and esper releases.Can you please tell me how to run an example so that i can see how the storm-esper integration works?Thanks

**Comment by miguelantonio** [comment]
Yeah you can use maven for that mvn -Dtest=TestxXXXX or just use mvn install or mvn package and the tests will run
